theme: jekyll-theme-slate 
title: Christina Q.
description: Watch me grow. Let&apos;s Go!

layout: page
title: Reflections
perma-link: https://cquinn21.github.io/.github.io-reading-notes/reflections/
